### ISSUE TITLE
need support for B205 mini 

### ISSUE THREAD

**Issue by nixilin** [RangeNetworks/OpenBTS-UMTS#17]
https://github.com/RangeNetworks/OpenBTS-UMTS/blob/master/TransceiverUHD/UHDDevice.cpp#L262

b205 mini almost same as b200?
just add a string detect logic and recompile/make ?

Thank you.

**Comment by AlisterAmo** [comment]
use this fork. of ours:
https://github.com/EurecatSecurity/OpenBTS-UMTS

**Comment by sebafonte** [comment]
Fork pending? i have seen some branch patching the string check, but is there other problem there?

**Comment by vipulpjain** [comment]
Hi Nixilin,

Does it work on B205 mini after adding the detect string for B205 mini?

Thanks,
Vipul
